module JekyllAndHyde
  class Setup < JekyllAndHyde::SingleTask
    desc "github", "Create branching information for GitHub Project Pages, details in http://pages.github.com/."

    def github
      validate_current_folder
      check_uncommited_files
      create_github_page_branch
      say
      print_next_steps
      say
    end

    private

    def validate_current_folder
      self.class.source_root(destination_root)
      find_in_source_paths("_config.yml")
    end

    def check_uncommited_files
      output = run_command 'git status'
      raise Error, "There are uncommited changes. Please commit them first." unless output =~ /.*nothing to commit.*/
    end

    def create_github_page_branch
      run_command 'git commit -am "Template files generated by jekyll_and_hyde."'
      run_command 'git checkout -b gh-pages'
      run_command 'git branch -d master'
      say_status :create, 'branch "gh-pages" for GitHub project page, details in http://pages.github.com/.'
    end

    def print_next_steps
      next_step_string = "Next steps:"
      say set_color(next_step_string, :blue, true)
      say "-" * next_step_string.size
      say 'git remote add origin git@github.com:your_github_username/your_git_repo.git'
      say 'git push origin gh-pages'
    end
  end
end